// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// all_deltas
IntegerVector all_deltas(NumericVector value, int k, double delta);
RcppExport SEXP _facereaderconverter_all_deltas(SEXP valueSEXP, SEXP kSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(all_deltas(value, k, delta));
    return rcpp_result_gen;
END_RCPP
}
// hysteresis_state
LogicalVector hysteresis_state(NumericVector v, int k, double T_up, double T_down, double delta, int min_len, int consecutive_missing);
RcppExport SEXP _facereaderconverter_hysteresis_state(SEXP vSEXP, SEXP kSEXP, SEXP T_upSEXP, SEXP T_downSEXP, SEXP deltaSEXP, SEXP min_lenSEXP, SEXP consecutive_missingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type T_up(T_upSEXP);
    Rcpp::traits::input_parameter< double >::type T_down(T_downSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type min_len(min_lenSEXP);
    Rcpp::traits::input_parameter< int >::type consecutive_missing(consecutive_missingSEXP);
    rcpp_result_gen = Rcpp::wrap(hysteresis_state(v, k, T_up, T_down, delta, min_len, consecutive_missing));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_facereaderconverter_all_deltas", (DL_FUNC) &_facereaderconverter_all_deltas, 3},
    {"_facereaderconverter_hysteresis_state", (DL_FUNC) &_facereaderconverter_hysteresis_state, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_facereaderconverter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
