# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

all_deltas <- function(value, k, delta) {
    .Call(`_facereaderconverter_all_deltas`, value, k, delta)
}

hysteresis_state <- function(v, k, T_up, T_down, delta, min_len, consecutive_missing) {
    .Call(`_facereaderconverter_hysteresis_state`, v, k, T_up, T_down, delta, min_len, consecutive_missing)
}

max_delta_ranges <- function(value, start_row, end_row, group_start_row, k) {
    .Call(`_facereaderconverter_max_delta_ranges`, value, start_row, end_row, group_start_row, k)
}

